packages:
  - .

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - crossws@0.4.12
  - db0@0.4.0
  - env-runner@0.2.0
  - h3@2.0.1-rc.29
  - nitro-nightly@3.0.1-20260820-230451-26928884
  - srvx@0.12.7
  - unstorage@2.0.0-alpha.9

onlyBuiltDependencies:
  - esbuild
  - lightningcss
